databases:
  - name: quizbase-db

services:
  - type: web
    name: quizbase-backend
    runtime: node
    rootDir: backend
    buildCommand: |
      npm install
      npm run build
      npx prisma migrate deploy
      npx prisma generate
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "4000"
      - key: DATABASE_URL
        fromDatabase:
          name: quizbase-db
          property: connectionString
      - key: CORS_ORIGIN
        value: https://your-frontend.onrender.com
      - key: FRONTEND_URL
        value: https://your-frontend.onrender.com
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRY
        value: 15m
      - key: JWT_REFRESH_EXPIRY
        value: 7d
      - key: BCRYPT_ROUNDS
        value: "12"

  - type: web
    name: quizbase-frontend
    runtime: static
    rootDir: frontend/quizbase
    buildCommand: |
      npm install
      npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://your-backend.onrender.com/api
      - key: VITE_SOCKET_URL
        value: https://your-backend.onrender.com
