version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: quizbase-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: quizbase
      POSTGRES_PASSWORD: quizbase
      POSTGRES_DB: quizbase
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quizbase"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
